---
safe: true
permalink: none
exclude:
- build.sh
- Gemfile
- Gemfile.lock
- Rakefile
- debian
- VERSION
- CNAME
- LICENSE
- README.md
title: "Hector Blanco"
description: "Hector Blanco's Portfolio"
markdown: redcarpet
domain: hectorblanco.eu
