---
safe: true
permalink: none
exclude:
- build.sh
- Gemfile
- Gemfile.lock
- Rakefile
- debian
- VERSION
title: "Hector Blanco's website"
description: "Hector Blanco's website"
markdown: redcarpet
highlighter: pygments
domain: hectorblanco.eu
