// Generated by CoffeeScript 1.12.2
$(function() {
  var aboutSection, aboutSectionScene, activityIndicatorOff, activityIndicatorOn, captionOff, captionOn, closeNavigations, contactSection, contactSectionScene, enableAboutSection, enableContactSection, enableDesignerSkills, enableGallerySection, enableHomeSection, enableLanguageSkills, enableSkillBar, enableSkillsSection, enableSoftwareSkills, enableWebSkills, gallery, galleryMenuScene, gallerySection, gallerySectionScene, getAboutHeight, getContactHeight, getGalleryHeight, getHomeHeight, getSkillsHeight, goToUrl, highlightSection, homeSection, homeSectionScene, lazySource, loadDesignerSkillsScene, loadImage, loadLanguageSkillsScene, loadSoftwareSkillsScene, loadWebSkillsScene, menuHeightOffset, overlayOff, overlayOn, parallaxScene, parallaxTween, placeholder, sceneHeights, scrollController, scrollToTarget, skillsSection, skillsSectionScene, topMenuScene, updateAboutHeight, updateContactHeight, updateGalleryHeight, updateHomeHeight, updateScenes, updateSkillsHeight, w;
  w = $(window);
  Modernizr.addTest('highresdisplay', function() {
    var mq;
    if (!window.matchMedia) {
      return;
    }
    mq = window.matchMedia("only screen and (-moz-min-device-pixel-ratio: 1.3), only screen and (-o-min-device-pixel-ratio: 2.6/2), only screen and (-webkit-min-device-pixel-ratio: 1.3), only screen  and (min-device-pixel-ratio: 1.3), only screen and (min-resolution: 1.3dppx)");
    if (mq && mq.matches) {
      return true;
    }
  });
  homeSection = $("#home");
  aboutSection = $("#about");
  gallerySection = $("#gallery");
  skillsSection = $("#skills");
  contactSection = $("#contact");
  menuHeightOffset = $("#navbar-menu").outerHeight() * -1;
  $("body").removeClass("preload");
  lazySource = Modernizr.highresdisplay ? "original-rd" : "original";
  placeholder = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC";
  $(".img-lazy").each(function() {
    var imgSource, ref, self;
    self = $(this);
    if (self.parent().is(":visible")) {
      if (self.is("img")) {
        self.attr("src", placeholder);
      }
      imgSource = (ref = self.data(lazySource)) != null ? ref : self.data("original");
      return self.one("appear", function() {
        return $("<img />").bind("load", function() {
          return loadImage(self, imgSource);
        }).attr("src", imgSource);
      });
    }
  });
  loadImage = function(self, imgSource) {
    self.hide();
    if (self.is("img")) {
      self.attr("src", imgSource);
    } else {
      self.css("background-image", "url('" + imgSource + "')");
    }
    self.fadeIn("slow");
    return self.removeClass("img-lazy").removeAttr("data-original").removeAttr("data-original-rd");
  };
  homeSection.find(".img-lazy").trigger("appear");
  setTimeout((function() {
    return aboutSection.find(".img-lazy").trigger("appear");
  }), 200);
  setTimeout((function() {
    return gallerySection.find(".img-lazy").trigger("appear");
  }), 400);
  setTimeout((function() {
    return skillsSection.find(".img-lazy").trigger("appear");
  }), 600);
  setTimeout((function() {
    return contactSection.find(".img-lazy").trigger("appear");
  }), 800);
  gallery = $("#gallery .gallery").isotope({
    layoutMode: 'masonry',
    itemSelector: '.gallery-item',
    masonry: {
      isFitWidth: true
    }
  });
  $("#navbar-gallery .gallery-filter a").click(function() {
    var filter;
    scrollToTarget(gallerySection);
    filter = $(this).data("filter");
    gallery.isotope({
      filter: "." + filter
    });
    updateScenes();
    gallerySection.find(".img-lazy").trigger("appear");
    $("#navbar-gallery .gallery-filter .navbar-item").removeClass("active");
    $(this).parent(".navbar-item").addClass("active");
    closeNavigations();
    return false;
  });
  activityIndicatorOn = function() {
    return $("#lightbox-loading").show();
  };
  activityIndicatorOff = function() {
    return $("#lightbox-loading").hide();
  };
  overlayOn = function() {
    $("#lightbox-overlay").show();
    return $("body").addClass("noscroll");
  };
  overlayOff = function() {
    $("body").removeClass("noscroll");
    return $("#lightbox-overlay").fadeOut("fast");
  };
  captionOn = function() {
    var body, caption, image, selectedImage, title;
    selectedImage = $("#imagelightbox").attr("src");
    image = $("a[href='" + selectedImage + "'] img");
    title = image.attr("alt");
    body = image.data("caption");
    if (title.length > 0 || body.length > 0) {
      caption = $("#lightbox-caption");
      caption.find(".title").text(title);
      caption.find(".body").text(body);
      return caption.show();
    }
  };
  captionOff = function() {
    return $("#lightbox-caption").fadeOut("fast");
  };
  $("#gallery .gallery-item a").imageLightbox({
    onStart: function() {
      return overlayOn();
    },
    onEnd: function() {
      captionOff();
      overlayOff();
      return activityIndicatorOff();
    },
    onLoadStart: function() {
      captionOff();
      return activityIndicatorOn();
    },
    onLoadEnd: function() {
      captionOn();
      return activityIndicatorOff();
    }
  });
  closeNavigations = function() {
    return $(".navbar-collapse.in").slideUp("fast", function() {
      return $(this).removeClass("in");
    });
  };
  $(".navbar .navbar-item").click(function() {
    return closeNavigations();
  });
  $(".navbar .navbar-toggle").click(function() {
    var collapsedNavId;
    collapsedNavId = $(this).data("target");
    return $(collapsedNavId).slideToggle("fast", function() {
      return $(this).toggleClass("in");
    });
  });
  scrollController = new ScrollMagic();
  sceneHeights = {};
  getHomeHeight = function() {
    return sceneHeights.home;
  };
  updateHomeHeight = function() {
    return sceneHeights.home = homeSection.outerHeight();
  };
  getAboutHeight = function() {
    return sceneHeights.about;
  };
  updateAboutHeight = function() {
    return sceneHeights.about = aboutSection.outerHeight();
  };
  getGalleryHeight = function() {
    return sceneHeights.gallery;
  };
  updateGalleryHeight = function() {
    return sceneHeights.gallery = gallerySection.outerHeight();
  };
  getSkillsHeight = function() {
    return sceneHeights.skills;
  };
  updateSkillsHeight = function() {
    return sceneHeights.skills = skillsSection.outerHeight();
  };
  getContactHeight = function() {
    return sceneHeights.contact;
  };
  updateContactHeight = function() {
    return sceneHeights.contact = contactSection.outerHeight();
  };
  updateScenes = function() {
    updateHomeHeight();
    updateAboutHeight();
    updateGalleryHeight();
    updateSkillsHeight();
    return updateContactHeight();
  };
  updateScenes();
  w.on("resize", updateScenes);
  enableSkillBar = function(bar) {
    return bar.find(".graph .bar").addClass("loaded");
  };
  enableDesignerSkills = function() {
    return enableSkillBar(skillsSection.find("#designer-skills"));
  };
  enableSoftwareSkills = function() {
    return enableSkillBar(skillsSection.find("#software-skills"));
  };
  enableWebSkills = function() {
    return enableSkillBar(skillsSection.find("#web-skills"));
  };
  enableLanguageSkills = function() {
    return enableSkillBar(skillsSection.find("#language-skills"));
  };
  if (Modernizr.touch) {
    skillsSection.find(".skill-bars").each(function() {
      return enableSkillBar($(this));
    });
  } else {
    loadDesignerSkillsScene = new ScrollScene({
      triggerElement: "#designer-skills",
      triggerHook: 0.5
    });
    loadDesignerSkillsScene.on("enter", enableDesignerSkills).addTo(scrollController);
    loadSoftwareSkillsScene = new ScrollScene({
      triggerElement: "#software-skills",
      triggerHook: 0.5
    });
    loadSoftwareSkillsScene.on("enter", enableSoftwareSkills).addTo(scrollController);
    loadWebSkillsScene = new ScrollScene({
      triggerElement: "#web-skills",
      triggerHook: 0.5
    });
    loadWebSkillsScene.on("enter", enableWebSkills).addTo(scrollController);
    loadLanguageSkillsScene = new ScrollScene({
      triggerElement: "#language-skills",
      triggerHook: 0.5
    });
    loadLanguageSkillsScene.on("enter", enableLanguageSkills).addTo(scrollController);
  }
  if (Modernizr.touch) {
    $(".scroll-layers").addClass("fluid");
  }
  if (!$(".scroll-layers").hasClass("fluid")) {
    parallaxTween = new TimelineMax();
    parallaxTween.add([
      TweenMax.to("#home .scroll-layers .layer1, #home .scroll-layers .layer2", 2, {
        backgroundPosition: "center -200px",
        ease: Linear.easeNone
      }), TweenMax.to("#home .scroll-layers .layer3", 2, {
        backgroundPosition: "center -300px",
        ease: Linear.easeNone
      }), TweenMax.to("#home .scroll-layers .layer4", 2, {
        backgroundPosition: "center -450px",
        ease: Linear.easeNone
      })
    ]);
    parallaxScene = new ScrollScene({
      triggerElement: "#home",
      triggerHook: 0,
      offset: 0,
      duration: $("#home").height()
    });
    parallaxScene.setTween(parallaxTween).addTo(scrollController);
  }
  topMenuScene = new ScrollScene({
    triggerElement: "#navbar-menu",
    triggerHook: 0,
    offset: 0
  });
  topMenuScene.setPin("#navbar-menu", {
    pinnedClass: "navbar-stuck"
  }).addTo(scrollController);
  galleryMenuScene = new ScrollScene({
    triggerElement: "#navbar-gallery",
    triggerHook: 0,
    offset: menuHeightOffset,
    duration: getGalleryHeight
  });
  galleryMenuScene.setPin("#navbar-gallery", {
    pinnedClass: "navbar-stuck",
    pushFollowers: false
  }).addTo(scrollController);
  highlightSection = function(sectionId) {
    var menuSections;
    menuSections = $("#navbar-menu li.navbar-item");
    menuSections.removeClass("active");
    return menuSections.has("a[href~='" + sectionId + "']").addClass("active");
  };
  enableHomeSection = function() {
    return highlightSection(homeSection.attr("id"));
  };
  enableAboutSection = function() {
    return highlightSection(aboutSection.attr("id"));
  };
  enableGallerySection = function() {
    return highlightSection(gallerySection.attr("id"));
  };
  enableSkillsSection = function() {
    return highlightSection(skillsSection.attr("id"));
  };
  enableContactSection = function() {
    return highlightSection(contactSection.attr("id"));
  };
  homeSectionScene = new ScrollScene({
    triggerElement: "#" + (homeSection.attr("id")),
    triggerHook: 0,
    offset: menuHeightOffset,
    duration: getHomeHeight
  });
  homeSectionScene.on("enter", enableHomeSection).addTo(scrollController);
  aboutSectionScene = new ScrollScene({
    triggerElement: "#" + (aboutSection.attr("id")),
    triggerHook: 0,
    offset: menuHeightOffset,
    duration: getAboutHeight
  });
  aboutSectionScene.on("enter", enableAboutSection).addTo(scrollController);
  gallerySectionScene = new ScrollScene({
    triggerElement: "#" + (gallerySection.attr("id")),
    triggerHook: 0,
    offset: menuHeightOffset,
    duration: getGalleryHeight
  });
  gallerySectionScene.on("enter", enableGallerySection).addTo(scrollController);
  skillsSectionScene = new ScrollScene({
    triggerElement: "#" + (skillsSection.attr("id")),
    triggerHook: 0,
    offset: menuHeightOffset,
    duration: getSkillsHeight
  });
  skillsSectionScene.on("enter", enableSkillsSection).addTo(scrollController);
  contactSectionScene = new ScrollScene({
    triggerElement: "#" + (contactSection.attr("id")),
    triggerHook: 0,
    offset: menuHeightOffset,
    duration: getContactHeight
  });
  contactSectionScene.on("enter", enableContactSection).addTo(scrollController);
  goToUrl = function(url, e) {
    var target;
    if (url == null) {
      return;
    }
    target = $("#" + url);
    if (target.length > 0) {
      if (e == null) {
        e.preventDefault();
      }
      scrollToTarget(target);
      return false;
    }
  };
  scrollToTarget = function(target, offset) {
    var targetId, targetOffset;
    if (offset == null) {
      offset = 0;
    }
    if (!(target && target.length > 0)) {
      return;
    }
    targetOffset = target.offset().top + menuHeightOffset + offset;
    targetId = target.attr("id");
    if (targetOffset !== w.scrollTop()) {
      return $("html,body").animate({
        scrollTop: targetOffset
      }, {
        duration: 500,
        complete: function() {
          return highlightSection(target.attr("id"));
        }
      });
    }
  };
  return $(document).on("click", "*[data-navigate=true]", function(e) {
    return goToUrl($(this).attr("href"), e);
  });
});
